# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-22 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191208_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateField(db_index=True, default=datetime.datetime(2019, 12, 22, 12, 7, 14, 175790), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 22, 12, 7, 14, 175790), verbose_name='Дата'),
        ),
    ]
